[tool.poetry]
name = "demo-auth"
version = "0.1.0"
description = ""
authors = ["nahmet"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^4.2.26"
django-environ = "^0.12.0"
psycopg2 = "^2.9.11"
djangorestframework = "^3.16.1"
pyjwt = "^2.10.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"
pytest-django = "^4.11.1"
freezegun = "^1.5.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
